// EDR Platform - gRPC Service Definition
// Version: 1.0.0
//
// This file defines the core gRPC services for agent-server communication
// including event ingestion, heartbeat monitoring, certificate management,
// and agent registration.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.3
// source: proto/v1/edr.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventIngestionService_StreamEvents_FullMethodName              = "/edr.v1.EventIngestionService/StreamEvents"
	EventIngestionService_Heartbeat_FullMethodName                 = "/edr.v1.EventIngestionService/Heartbeat"
	EventIngestionService_RequestCertificateRenewal_FullMethodName = "/edr.v1.EventIngestionService/RequestCertificateRenewal"
	EventIngestionService_RegisterAgent_FullMethodName             = "/edr.v1.EventIngestionService/RegisterAgent"
	EventIngestionService_SendCommandResult_FullMethodName         = "/edr.v1.EventIngestionService/SendCommandResult"
)

// EventIngestionServiceClient is the client API for EventIngestionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EventIngestionService handles all agent-to-server communication
type EventIngestionServiceClient interface {
	// StreamEvents - Bidirectional streaming for event ingestion
	// Agent sends EventBatch messages, server responds with CommandBatch
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EventBatch, CommandBatch], error)
	// Heartbeat - Periodic health check from agent
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// RequestCertificateRenewal - Agent requests new certificate before expiry
	RequestCertificateRenewal(ctx context.Context, in *CertRenewalRequest, opts ...grpc.CallOption) (*CertificateResponse, error)
	// RegisterAgent - Initial agent registration with installation token
	RegisterAgent(ctx context.Context, in *AgentRegistrationRequest, opts ...grpc.CallOption) (*AgentRegistrationResponse, error)
	// SendCommandResult - Agent sends command execution result back to server (C2 feedback)
	SendCommandResult(ctx context.Context, in *CommandResult, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type eventIngestionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventIngestionServiceClient(cc grpc.ClientConnInterface) EventIngestionServiceClient {
	return &eventIngestionServiceClient{cc}
}

func (c *eventIngestionServiceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EventBatch, CommandBatch], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventIngestionService_ServiceDesc.Streams[0], EventIngestionService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventBatch, CommandBatch]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventIngestionService_StreamEventsClient = grpc.BidiStreamingClient[EventBatch, CommandBatch]

func (c *eventIngestionServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, EventIngestionService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventIngestionServiceClient) RequestCertificateRenewal(ctx context.Context, in *CertRenewalRequest, opts ...grpc.CallOption) (*CertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateResponse)
	err := c.cc.Invoke(ctx, EventIngestionService_RequestCertificateRenewal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventIngestionServiceClient) RegisterAgent(ctx context.Context, in *AgentRegistrationRequest, opts ...grpc.CallOption) (*AgentRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentRegistrationResponse)
	err := c.cc.Invoke(ctx, EventIngestionService_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventIngestionServiceClient) SendCommandResult(ctx context.Context, in *CommandResult, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EventIngestionService_SendCommandResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventIngestionServiceServer is the server API for EventIngestionService service.
// All implementations must embed UnimplementedEventIngestionServiceServer
// for forward compatibility.
//
// EventIngestionService handles all agent-to-server communication
type EventIngestionServiceServer interface {
	// StreamEvents - Bidirectional streaming for event ingestion
	// Agent sends EventBatch messages, server responds with CommandBatch
	StreamEvents(grpc.BidiStreamingServer[EventBatch, CommandBatch]) error
	// Heartbeat - Periodic health check from agent
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// RequestCertificateRenewal - Agent requests new certificate before expiry
	RequestCertificateRenewal(context.Context, *CertRenewalRequest) (*CertificateResponse, error)
	// RegisterAgent - Initial agent registration with installation token
	RegisterAgent(context.Context, *AgentRegistrationRequest) (*AgentRegistrationResponse, error)
	// SendCommandResult - Agent sends command execution result back to server (C2 feedback)
	SendCommandResult(context.Context, *CommandResult) (*emptypb.Empty, error)
	mustEmbedUnimplementedEventIngestionServiceServer()
}

// UnimplementedEventIngestionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventIngestionServiceServer struct{}

func (UnimplementedEventIngestionServiceServer) StreamEvents(grpc.BidiStreamingServer[EventBatch, CommandBatch]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedEventIngestionServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedEventIngestionServiceServer) RequestCertificateRenewal(context.Context, *CertRenewalRequest) (*CertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestCertificateRenewal not implemented")
}
func (UnimplementedEventIngestionServiceServer) RegisterAgent(context.Context, *AgentRegistrationRequest) (*AgentRegistrationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedEventIngestionServiceServer) SendCommandResult(context.Context, *CommandResult) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCommandResult not implemented")
}
func (UnimplementedEventIngestionServiceServer) mustEmbedUnimplementedEventIngestionServiceServer() {}
func (UnimplementedEventIngestionServiceServer) testEmbeddedByValue()                               {}

// UnsafeEventIngestionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventIngestionServiceServer will
// result in compilation errors.
type UnsafeEventIngestionServiceServer interface {
	mustEmbedUnimplementedEventIngestionServiceServer()
}

func RegisterEventIngestionServiceServer(s grpc.ServiceRegistrar, srv EventIngestionServiceServer) {
	// If the following call panics, it indicates UnimplementedEventIngestionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventIngestionService_ServiceDesc, srv)
}

func _EventIngestionService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventIngestionServiceServer).StreamEvents(&grpc.GenericServerStream[EventBatch, CommandBatch]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventIngestionService_StreamEventsServer = grpc.BidiStreamingServer[EventBatch, CommandBatch]

func _EventIngestionService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventIngestionServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventIngestionService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventIngestionServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventIngestionService_RequestCertificateRenewal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertRenewalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventIngestionServiceServer).RequestCertificateRenewal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventIngestionService_RequestCertificateRenewal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventIngestionServiceServer).RequestCertificateRenewal(ctx, req.(*CertRenewalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventIngestionService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventIngestionServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventIngestionService_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventIngestionServiceServer).RegisterAgent(ctx, req.(*AgentRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventIngestionService_SendCommandResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventIngestionServiceServer).SendCommandResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventIngestionService_SendCommandResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventIngestionServiceServer).SendCommandResult(ctx, req.(*CommandResult))
	}
	return interceptor(ctx, in, info, handler)
}

// EventIngestionService_ServiceDesc is the grpc.ServiceDesc for EventIngestionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventIngestionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "edr.v1.EventIngestionService",
	HandlerType: (*EventIngestionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _EventIngestionService_Heartbeat_Handler,
		},
		{
			MethodName: "RequestCertificateRenewal",
			Handler:    _EventIngestionService_RequestCertificateRenewal_Handler,
		},
		{
			MethodName: "RegisterAgent",
			Handler:    _EventIngestionService_RegisterAgent_Handler,
		},
		{
			MethodName: "SendCommandResult",
			Handler:    _EventIngestionService_SendCommandResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _EventIngestionService_StreamEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/v1/edr.proto",
}
