package detection

import (
	"strings"

	"github.com/edr-platform/sigma-engine/internal/domain"
)

// agentSelfMarkers are case-insensitive substrings that uniquely identify the
// EDR agent's own executable. Any event whose parent (or originating) process
// matches one of these is considered "self" telemetry and is suppressed at the
// detection-engine entry point as a defense-in-depth layer behind the agent's
// own collector-level self-exclusion.
//
// Why this exists:
//
//	The agent occasionally spawns short-lived helper processes (PowerShell for
//	WMI queries, network adapter inspection, etc.) and used to enumerate them
//	through its own WMI collector, causing self-inflicted T1059/T1021 alerts.
//	The agent now filters these locally, but a server-side guard ensures the
//	platform stays clean even if an older / misbehaving agent re-introduces
//	the regression, or if telemetry arrives from an alternate ingestion path.
//
// Markers cover both the canonical install path and the bare executable name
// so the check works on relocated or service-managed installations.
var agentSelfMarkers = []string{
	`\programdata\edr\bin\edr-agent.exe`,
	`\programdata\edr\bin\agent.exe`,
	`\program files\edr\edr-agent.exe`,
	`\program files\edr\agent.exe`,
	`\edr-agent.exe`,
	`\edr_agent.exe`,
}

// agentSelfBaseNames matches process basenames only (used when the full path
// is not available, e.g. bare process_name from sysmon ParentImage parsing).
var agentSelfBaseNames = map[string]struct{}{
	"edr-agent.exe": {},
	"edr_agent.exe": {},
}

// parentFieldPaths is the ordered list of fields the engine inspects to decide
// whether an event was produced by an agent child. The order matches the most
// specific (full path) → least specific (basename) so we short-circuit early.
//
// Coverage rationale:
//   - parent_executable / parent_image: emitted by the Windows agent ETW &
//     WMI collectors and Sysmon-normalised events.
//   - ParentImage: native Sigma field (Sysmon EventID 1 / Microsoft-Windows-
//     Sysmon channel).
//   - parent_path / ParentProcessName: alternative fields used by some
//     collectors / normalisers.
//   - parent_name / ParentProcessName basename: last-resort match.
var parentFieldPaths = []string{
	"parent_executable",
	"parent_image",
	"ParentImage",
	"parent_path",
	"ParentProcessName",
	"parent_name",
	"ParentName",
}

// isAgentSelfEvent reports whether the event was generated by the EDR agent
// or one of its direct child processes. The check is intentionally cheap —
// a handful of case-insensitive substring matches per event — so it adds no
// measurable overhead to the detection hot path.
func isAgentSelfEvent(event *domain.LogEvent) bool {
	if event == nil {
		return false
	}

	for _, path := range parentFieldPaths {
		raw := event.GetStringField(path)
		if raw == "" {
			continue
		}
		v := strings.ToLower(raw)

		// Full-path match (preferred).
		for _, marker := range agentSelfMarkers {
			if strings.Contains(v, marker) {
				return true
			}
		}

		// Basename-only match (fallback when only "edr-agent.exe" is present).
		if _, ok := agentSelfBaseNames[v]; ok {
			return true
		}
		// Some sources carry the basename with a leading separator stripped.
		if idx := strings.LastIndexAny(v, `\/`); idx >= 0 {
			if _, ok := agentSelfBaseNames[v[idx+1:]]; ok {
				return true
			}
		}
	}

	return false
}
